api_platform:
    title: 'API para Gestión de Reservas'
    description: 'API para gestionar reservas de espacios'
    version: 1.0.0
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
