security:
    # Configuración de hash de contraseñas
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    # Configuración de proveedores de usuario
    providers:
        users_in_memory: { memory: null }
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Desactivar la seguridad para login y register
        login:
            pattern: ^/api/login
            security: false

        register:
            pattern: ^/api/register
            security: false

        # Configuración para la API con JWT
        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider

            # json_login para manejar la autenticación de login
            json_login:
                check_path: /api/login
                username_path: username
                password_path: password

            # Habilitar JWT para las rutas protegidas
            jwt: ~

    # Control de acceso
    access_control:
        # Permitir el acceso anónimo a las rutas de login y registro
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api/docs, roles: PUBLIC_ACCESS }
        - { path: ^/api/check-username, roles: PUBLIC_ACCESS }
        # Restringir el acceso a las rutas de la API para usuarios autenticados
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
